POST http://localhost:3000/register
Content-Type:application/json

{
  "username": "sai teja",
  "name": "Adam Richard",
  "password": "ravi_567",
  "gender": "male",
  "location": "Detroit"
}
###

POST http://localhost:3000/login
Content-Type:application/json

{
  "username": "sai teja",
  "password": "ravi_567"
}
###

PUT http://localhost:3000/change-password
Content-Type:application/json

{
  "username": "sai teja",
  "oldPassword": "ravi_567",
  "newPassword": "richard@123"
}
